language: node_js
node_js:
- 8.9.4
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
- yarn build
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_0aa1b4300bcd_key -iv $encrypted_0aa1b4300bcd_iv
  -in deploy.enc -out /tmp/deploy -d
